const chrisShop = [
    {
        nom: 'motoba', 
        prenom: 'claude', 
        postNom: 'anyabiki', 
        matricule: '000001', 
        age: 25, 
        sexe: 'M', 
        nationalite: 'congolaise', 
        poste: 'developpeur front-end',
        competences: 'html,css,javascript',
        tel: +243000000001,
        adresse: '',
    },
    {
        nom: 'makengo', 
        prenom: 'stanislas', 
        postNom: 'pembele', 
        matricule: '000002', 
        age: 20, 
        sexe: 'M', 
        nationalite: 'congolaise', 
        poste: 'developpeur front-end',
        competences: '',
        tel: +243000000002,
        adresse: '',
    },
    {
        nom: 'kangudi', 
        prenom: 'murdock', 
        postNom: '', 
        matricule: '000003', 
        age: 22, 
        sexe: 'M', 
        nationalite: 'congolaise', 
        poste: 'developpeur front-end',
        competences: 'html,css,javascript',
        tel: +243000000003,
        adresse: '',
    },
    {
        nom: 'liyalo', 
        prenom: 'dieu-donné', 
        postNom: '', 
        matricule: '000004', 
        age: 26, 
        sexe: 'M', 
        nationalite: 'congolaise', 
        poste: 'developpeur back-end',
        competences: 'php,nodejs,python',
        tel: +243000000004,
        adresse: '',
    },
    {
        nom: 'ilali', 
        prenom: 'axel', 
        postNom: 'pembele', 
        matricule: '000005', 
        age: 30, 
        sexe: 'M', 
        nationalite: 'congolaise', 
        poste: 'developpeur back-end',
        competences: 'php,nodejs,python',
        tel: +243000000005,
        adresse: '',
    },
    {
        nom: 'kalala', 
        prenom: 'jonathan', 
        postNom: 'pembele', 
        matricule: '000006', 
        age: 20, 
        sexe: 'M', 
        nationalite: 'congolaise', 
        poste: 'developpeur back-end',
        competences: 'php,nodejs,python',
        tel: +243000000006,
        adresse: '',
    },
    {
        nom: 'binene', 
        prenom: 'iggort', 
        postNom: 'pembele', 
        matricule: '000007', 
        age: 20, 
        sexe: 'M', 
        nationalite: 'congolaise', 
        poste: 'designers',
        competences: 'photoshop,figma,indesign,illustrator',
        tel: +243000000007,
        adresse: '',
    },
    {
        nom: 'fakala', 
        prenom: 'russel', 
        postNom: '', 
        matricule: '000008', 
        age: 16, 
        sexe: 'f', 
        nationalite: 'congolaise', 
        poste: 'Designers',
        competences: 'photoshop,figma,indesign,illustrator',
        tel: +243000000008,
        adresse: '',
    },
    {
        nom: 'mapwata', 
        prenom: 'gael', 
        postNom: 'pembele', 
        matricule: '000009', 
        age: 28, 
        sexe: 'M', 
        nationalite: 'congolaise', 
        poste: 'Designers',
        competences: 'photoshop,figma,indesign,illustrator',
        tel: +243000000009,
        adresse: '',
    },
    {
        nom: 'lusevakio', 
        prenom: 'semia', 
        postNom: 'pembele', 
        matricule: '000010', 
        age: 15, 
        sexe: 'f', 
        nationalite: 'congolaise', 
        poste: 'commercial',
        competences: 'communication,marketing',
        tel: +243000000010,
        adresse: '',
    },
    {
        nom: 'manzako', 
        prenom: 'jonathan', 
        postNom: 'pembele', 
        matricule: '000011', 
        age: 31, 
        sexe: 'M', 
        nationalite: 'congolaise', 
        poste: 'commercial',
        competences: 'communication,marketing',
        tel: +243000000011,
        adresse: '',
    },
    {
        nom: 'kabemba', 
        prenom: 'joseph', 
        postNom: 'pembele', 
        matricule: '000012', 
        age: 32, 
        sexe: 'M', 
        nationalite: 'congolaise', 
        poste: 'commercial',
        competences: 'communication,marketing',
        tel: +243000000012,
        adresse: '',
    },
    {
        nom: 'lisangola', 
        prenom: 'sarah', 
        postNom: 'pembele', 
        matricule: '000013', 
        age: 17, 
        sexe: 'f', 
        nationalite: 'congolaise', 
        poste: 'finance',
        competences: 'comptabilité,logisitique',
        tel: +243000000013,
        adresse: '',
    },
    {
        nom: 'disubi', 
        prenom: 'francois', 
        postNom: 'pembele', 
        matricule: '000014', 
        age: 34, 
        sexe: 'M', 
        nationalite: 'congolaise', 
        poste: 'finance',
        competences: 'comptabilité,logisitique',
        tel: +243000000014,
        adresse: '',
    },
    {
        nom: 'ben', 
        prenom: 'matanda', 
        postNom: 'pembele', 
        matricule: '000015', 
        age: 35, 
        sexe: 'M', 
        nationalite: 'congolaise', 
        poste: 'finance',
        competences: 'comptabilité,logisitique',
        tel: +243000000015,
        adresse: '',
    },
]
// 1. liste des employés
console.log(chrisShop);

// numero matricule
var matricule = chrisShop.find(element => element.matricule == '000001');
console.log(matricule);

// filtrer a partir du nom et du poste
var chriShop = chrisShop.filter (function (value) {
    return value.nom && value.poste;
}) 
console.log (chriShop);

//mineur de sexe feminin
var mineurDeSexeFeminin = chrisShop.filter (function(word){ 
     return word.age < 18 && word.sexe == 'f';
});
console.log(mineurDeSexeFeminin);



